#These are the configurable words, add to this inifnitely with proper formatting
#or add with the in-game command /wordadd
replace-words:
  fuck: flock
  shit: sheet
  cunt: cutie
  dick: dong
  ass: butt
